# Generated by Django 4.2.9 on 2024-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoboData',
            fields=[
                ('roboId', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
